version: "3.9"

services:
  gerenciamento:
    build:
      context: ./gerenciamento
    container_name: gerenciamento
    ports:
      - "5000:5000"
    volumes:
      - ./gerenciamento:/app
      - ./gerenciamento/database.db:/app/database.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

  reservas:
    build:
      context: ./reservas
    container_name: reservas
    ports:
      - "5001:5000"
    volumes:
      - ./reservas:/app
      - ./reservas/database.db:/app/database.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

